### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by justinmoon** [fedimint/fedimint-custom-modules-example#2]
- [ ] Get it to run in replit
- [ ] Write a test using `integrationtests`
- [ ] Eventually aybe make a "template" out of this where you can say the name of your module and it will scaffold out the module crates with the right names and everything. Probably not worth doing for some time.
